# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, blank=False, unique=True, verbose_name='name')),
                ('placeId', models.CharField(max_length=255, blank=False, unique=True, verbose_name='place id')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=b'date modified')),
            ],
        )
    ]
